### PR TITLE
add rOpenSci stats review content

### PR DESCRIPTION
**Pull request by mpadge**
This is an initial commit to see what you think of this approach. I have currently applied our initial automated assessment tools to your `riskmetric` package, and simply dumped all output in the blog post. Could you please first check one and only one of the following, and I'll continue accordingly:

- [ ] That is all too technical, and a more general and discursive overview would be preferred; or
- [x] That is okay because the intended audience will be sufficiently technically versed to appreciate that

Whatever comes, it'll probably be interesting for @dgkf and other `riskmetric` folk to see the output of [`autotest`](https://github.com/ropenscilabs/autotest) applied to the package.

---

EDIT: A lot of the aforementioned technical guff is in direct `html` form within the `.Rmd`, so a bit hard to see directly from the PR here what I've done. You'll likely need to spin up a local hugo instance to see the effect. Hope that's okay :smile:

### CODE REVIEW

**Comment by andyofsmeg** [comment]
Mark, it's looking good.  It is a lot of output but the pitch is right for me.

**Comment by mpadge** [comment]
Alright then I'll continue along that line. I'll also distil the technical aspects of the current content down as much as possible, to make it as discursive as I can. Thanks! I'll ping you within a day or two when I think I've got a first draft in a good enough state.

**Comment by dgkf** [comment]
Sorry for a bit of delay in taking a look. I love the autotest output - that looks super helpful, and agree that the content is appropriate for our audience. Some of the details of the items in the table might not sink in, but I think the core message will still land just fine without being able to interpret all of the messages raised by autotest. 

Some edits:
- There are some bullets at the bottom of the Rmd that look like they might be leftover from a draft version. 
- It would be great to include an rOpenSci logo in the banner image, similar to what we have for the Shiny app blog post where we highlighted the collaborations with the R Consortium and fissionlabs.

**Comment by mpadge** [comment]
I would like to suggest that the blog is now in at least a sufficient first-draft state. Comments & feedback welcome

**Review by jmanitz — APPROVED** [review]

**Comment by mpadge** [comment]
@jmanitz @andyofsmeg can you please just hold off merging until @noamross has had a chance to peruse it. Noam, a simple :+1: will suffice, or feel free to make any suggestions or changes as you see fit. Juliane & Andy: Noam was planning on heading off for a few days, so may not be able to get to it until next Wed (4th Nov) - hope that's okay. Thanks!

**Comment by andyofsmeg** [comment]
@mpadge - I've merged based on the email thread but this is only onto the preview branch and it won't go properly live until we create a new PR for master.  For now I will wait still.

**Comment by mpadge** [comment]
Thanks @andyofsmeg, I'll get back to you asap once @noamross has had a chance to look at it.

**Comment by andyofsmeg** [comment]
@mpadge , @noamross ,  have you had a follow-up discussion yet?

**Comment by mpadge** [comment]
I've reminded him a few times. He and i will be talking in about 4 hours time, and I'll push him once more. If you don't hear from him by the end of your today, then please just go ahead regardless. Thanks!

**Pull request merged**
